version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "3200:3200"
    volumes:
      - .:/app
    environment:
      - ENV_PATH=/app/env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
